#!/usr/bin/env python3
"""
run_all.py — Regenerates answers.md by running all 7 published questions.

Usage:
    python run_all.py
"""

import json
import sys
import time
from src.pipeline import RAGPipeline

QUESTIONS = [
    "I scored 78% and have a budget of ₹1.5 lakh/year — which engineering colleges can I consider?",
    "Which colleges offer an MBA, and what do they cost?",
    "List the government colleges that have hostel facilities.",
    "What's the average placement package at North Ridge Institute of Technology?",
    "Does Ganga Valley University offer a PhD in Physics?",
    "Which colleges offer scholarships for students from low-income families?",
    "Which college is best for me? I have ₹1 lakh per semester.",
]


def main():
    print("Initializing RAG pipeline (loading embeddings)...", file=sys.stderr)
    pipeline = RAGPipeline()
    print("Pipeline ready. Running 7 published questions...\n", file=sys.stderr)

    outputs = []
    total_input_tokens = 0
    total_output_tokens = 0
    total_latency = 0.0

    for i, q in enumerate(QUESTIONS, 1):
        print(f"[{i}/7] {q[:60]}...", file=sys.stderr)
        result = pipeline.answer(q, measure_cost=True)

        metrics = result.pop("_metrics", {})
        total_input_tokens += metrics.get("input_tokens", 0)
        total_output_tokens += metrics.get("output_tokens", 0)
        total_latency += metrics.get("latency_seconds", 0)

        outputs.append((q, result, metrics))

    # Write answers.md
    with open("answers.md", "w") as f:
        f.write("# answers.md — Verbatim system output for 7 published questions\n\n")
        f.write("Generated by `run_all.py`. Copy-pasted, not edited.\n\n")

        for i, (q, result, metrics) in enumerate(outputs, 1):
            f.write(f"---\n\n## Question {i}\n\n")
            f.write(f"**Query:** {q}\n\n")
            f.write(f"```json\n{json.dumps(result, indent=2, ensure_ascii=False)}\n```\n\n")
            f.write(f"*Tokens: {metrics.get('input_tokens', '?')} in / "
                    f"{metrics.get('output_tokens', '?')} out | "
                    f"Latency: {metrics.get('latency_seconds', '?')}s | "
                    f"Cost: ${metrics.get('cost_usd', '?')}*\n\n")

        # Summary
        n = len(QUESTIONS)
        f.write("---\n\n## Cost Summary\n\n")
        f.write(f"| Metric | Value |\n|---|---|\n")
        f.write(f"| Total queries | {n} |\n")
        f.write(f"| Avg input tokens/query | {total_input_tokens // n} |\n")
        f.write(f"| Avg output tokens/query | {total_output_tokens // n} |\n")
        f.write(f"| Avg latency/query | {total_latency / n:.2f}s |\n")
        f.write(f"| Total cost (7 queries) | ${sum(m.get('cost_usd', 0) for _, _, m in outputs):.6f} |\n")

    print(f"\n✅ answers.md written ({len(QUESTIONS)} questions)", file=sys.stderr)
    print(f"   Avg tokens: {total_input_tokens // n} in / {total_output_tokens // n} out", file=sys.stderr)
    print(f"   Avg latency: {total_latency / n:.2f}s", file=sys.stderr)


if __name__ == "__main__":
    main()
